Repository anmode/grabtern-frontend, pull requests merged in 2023-08, with the labels that each got.

#637 feat: Sidebar improvements/new navbar for mobile devices
  components/mentorDashboard/sidebar.js
  pages/dashboard/mentor.page.js
Labels: level3, gssoc23

#645 created secured site
  .env
  components/layout/Footer.js
  components/layout/UserProfile.js
  next.config.js
  package.json
  pages/[mentorUsername]/bookSession/index.page.js
  pages/auth/login.page.js
  pages/index.page.js
  styles/form.module.css
Labels: gssoc23

#642 [Fix] - Apis getting called without any input values
  pages/auth/forgotpass.page.js
  pages/auth/login.page.js
  pages/auth/register.page.js
  pages/auth/resetpassword.page.js
Labels: level2, gssoc23

#641 Mentor profile api connection
  components/mentorDashboard/profile.js
Labels: gssoc23

#587 added spinner in register page and login page
  .env
  components/eventLogin/EventLogin.js
  pages/auth/login.page.js
  pages/auth/register.page.js
Labels: level3, gssoc23

#649 added start and end time select box in schedule page
  components/mentorDashboard/calendar.js
  components/newMentorProfile/SessionCard.js
  package.json
  public/sitemap-0.xml
Labels: level3, gssoc23

#652 fixed spinner in mobile device
  components/eventLogin/EventLogin.js
  pages/auth/login.page.js
  pages/auth/register.page.js
  styles/form.module.css
Labels: level2, gssoc23

#656 Fix mentor dashboard page routes
  components/mentorDashboard/sidebar.js
  pages/dashboard/mentor.page.js
Labels: gssoc23

#567 Created Queries page for mentor dashboard
  components/mentorDashboard/queries.js
  components/mentorDashboard/sidebar.js
  components/mentorDashboard/ticketForm.js
  pages/dashboard/mentor.page.js
  styles/queries.module.css
Labels: level3, gssoc23

#658 feat: fixed reset password page
  components/eventLogin/EventLogin.js
  pages/auth/resetpassword.page.js
  styles/form.module.css
Labels: gssoc23

#660 fix: removed text in top-btn
  components/basic/MoveToTop.js
Labels: gssoc23

#655 feat: Create Changelog.yml ✨
  .github/workflows/Changelog.yml
Labels: level2, gssoc23

#665 Fix issue #627
  .github/workflows/codeql.yml
Labels: level1, gssoc23

#653 feat: add social links to share Profile. #629
  components/mentorProfile/components/SharePageModal.js
Labels: gssoc23

#585 [ADDED]: Button test file
  components/UI/Button/button.test.js
  jest.config.json
  package.json
Labels: gssoc23

#664 feat: made social anchors accessible on entire grabtern site 🚀🔥
  components/layout/Footer.js
  components/mentor.js
  components/mentorProfile/components/MentorCard.js
Labels: level2, gssoc23

#644 Updated Searchbar Input from MUI to Tailwind CSS
  components/hackthons/components/Searchbar.js
  public/assets/img/hackathons/magnifying-glass.png
Labels: gssoc23

#607 [ADDED]: Test File for Mentor Registration Form
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/MentorRegistrationForm.test.js
  package.json
Labels: gssoc23

#669 feat: homepage for ``dashboard/mentor``
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/MentorRegistrationForm.test.js
  components/UI/Button/button.test.js
  components/basic/MoveToTop.js
  components/eventLogin/EventLogin.js
  components/hackthons/components/Searchbar.js
  components/mentorDashboard/home.js
  components/mentorDashboard/sessions.js
  components/mentorDashboard/sidebar.js
  components/mentorProfile/components/SharePageModal.js
  pages/auth/resetpassword.page.js
  pages/dashboard/mentor.page.js
  styles/form.module.css
Labels: level3, gssoc23

#678 [Solved]: Workflow Issue
  components/UI/Button/button.test.js
  jest.config.json
  package.json
Labels: level2, gssoc23

#680 feat: mobile optimization for ``dashboard/mentor`` homepage
  components/mentorDashboard/home.js
Labels: level2, gssoc23

#683 Booking page backend connection
  components/mentorDashboard/Bookings.js
  components/mentorDashboard/home.js
Labels: gssoc23

#675 User dashboard Initialized
  components/userDashboard/Bookings.js
  components/userDashboard/home.js
  components/userDashboard/profile.js
  components/userDashboard/sidebar.js
  pages/dashboard/user.page.js
Labels: level3, gssoc23

#671 Add blog
  .env
  components/blog.js
  components/hackthons/Hackathons.js
  components/layout/Header.js
  pages/_app.page.js
  pages/_document.page.js
  pages/blogDetail/[blogDetailId].page.js
  pages/blogs.page.js
  styles/blogDetail.module.css
Labels: gssoc23

#690 feat: responsive design and optimization for queries page in dashboard/mentor
  components/mentorDashboard/home.js
  components/mentorDashboard/queries.js
  components/mentorDashboard/ticketForm.js
  pages/dashboard/mentor.page.js
  styles/queries.module.css
Labels: level3, gssoc23

#691 feat: responsive profile tab for mentor dashboard.
  components/mentorDashboard/profile.js
  public/assets/img/MentorImg.svg
  public/assets/index.js
Labels: level2, gssoc23

#692 Redesign Calendar feature
  components/mentorDashboard/CalendarComponent/card.js
  components/mentorDashboard/calendar.js
  package.json
  public/toggleOff.png
  public/toggleOn.png
Labels: level3, gssoc23

#694 Fixed the Confirm Password eye button
  pages/auth/register.page.js
  public/sitemap-0.xml
Labels: level1, gssoc23

#693 Contributor fetch
  components/Community/CommunityCard.jsx
  package.json
  pages/community.page.js
  pages/data/teamsData.js
Labels: level3, gssoc23

#699 feat: fixed color of grabtern logo in mentor dashboard
  components/mentorDashboard/sidebar.js
Labels: level1, gssoc23

#700 feat: improved queries page UI and optimized the page
  components/mentorDashboard/queries.js
  styles/queries.module.css
Labels: level2, gssoc23

#695 Redesign schedule feature in calendar section
  components/mentorDashboard/Schedule/schedule.js
  components/mentorDashboard/calendar.js
Labels: level3, gssoc23

#705 feat: fixed button hover color
  styles/globals.css
Labels: level2, gssoc23

#697 Mentor sessions api
  components/mentorDashboard/Bookings.js
  components/mentorDashboard/sessions.js
Labels: gssoc23

#703 feat: coming soon page
  components/Community/CommunityCard.jsx
  components/basic/ComingSoon.js
  components/mentorDashboard/queries.js
  pages/community.page.js
  pages/dashboard/mentor.page.js
  pages/data/teamsData.js
  public/assets/img/comingSoon.png
  public/assets/index.js
  styles/404.module.css
  styles/queries.module.css
Labels: level3, gssoc23

#712 fix: useeffects and removed annoying console logs
  components/UI/Button/Button.js
  components/hackthons/components/Searchbar.js
  pages/auth/forgotpass.page.js
  pages/auth/resetpassword.page.js
  pages/hackathon.page.js
Labels: level1, gssoc23

#702 Removing MUI and Improving UI with SVGs
  components/basic/SvgMaker.js
  package.json
  pages/auth/forgotpass.page.js
  pages/auth/resetpassword.page.js
  pages/hackathon.page.js
  pages/internship.page.js
  pages/mentor.page.js
Labels: gssoc23

#720 Added the no. of commits and contributors title .
  components/Community/CommunityCard.jsx
  components/UI/Button/Button.js
  components/basic/SvgMaker.js
  components/hackthons/components/Searchbar.js
  package.json
  pages/auth/forgotpass.page.js
  pages/blogDetail/blogDetail.page.js
  pages/community.page.js
  pages/hackathon.page.js
  pages/internship.page.js
  pages/mentor.page.js
Labels: level3, gssoc23

#727 feat: Optimization of Schedule tab in ``dashboard/mentor``
  components/mentorDashboard/Schedule/schedule.js
  components/mentorDashboard/calendar.js
Labels: level2, gssoc23

#711 Fix Session Page Of Mentor Dashboard
  components/mentorDashboard/sessions.js
  components/newMentorProfile/SessionCard.js
  pages/dashboard/editMentorSession.page.js
Labels: gssoc23

#729 feat: optimized Calender tab in ``dashboard/mentor/calender``
  components/mentorDashboard/CalendarComponent/card.js
  package.json
Labels: level2, gssoc23

#731 feat: add support to add new schedules in ``dashboard/mentor/calender``
  components/mentorDashboard/Schedule/schedule.js
  components/mentorDashboard/calendar.js
Labels: level3, gssoc23

#732 feat: add more features to payment page in ``dashboard/mentor/payment``
  components/mentorDashboard/Payment.js
Labels: level3, gssoc23

#730 Add Hashnode Newsletter Subscription and Confirmation Email
  components/layout/Footer.js
Labels: level2, gssoc23

#735 Edit mentor form
  components/mentorDashboard/sessions.js
  pages/dashboard/editMentorSession.page.js
Labels: level3, gssoc23

#737 feat: on click expand/collapse sidebar
  components/layout/Footer.js
  components/mentorDashboard/home.js
  components/mentorDashboard/sidebar.js
  pages/dashboard/mentor.page.js
Labels: level3, gssoc23

#738 feat: toggle to open/close sidebar
  components/mentorDashboard/sidebar.js
  package.json
  pages/dashboard/mentor.page.js
Labels: level2, gssoc23

#736 [feat]Added Loader
  components/basic/spinner.js
  components/mentorDashboard/Bookings.js
  components/mentorDashboard/sessions.js
  pages/dashboard/editMentorSession.page.js
  public/spinner.gif
Labels: level3, gssoc23

#740 Fixed MUI error in contact tab of mentor dashbord
  components/UI/Button/Switch.js
  components/UI/index.js
  components/mentorDashboard/CalendarComponent/card.js
Labels: level3, gssoc23

#742 Fix dashboard profile tab
  components/UI/Button/Switch.js
  components/UI/index.js
  components/mentorDashboard/CalendarComponent/card.js
  components/mentorDashboard/profile.js
Labels: level2, gssoc23

#739 Remove hover from cards
  components/mentorDashboard/Payment.js
  components/mentorDashboard/home.js
  components/mentorDashboard/profile.js
  components/mentorDashboard/queries.js
Labels: level2, gssoc23

#744 Added logout button on mentor dashboard
  components/mentorDashboard/home.js
Labels: level1, gssoc23

#724 userBooking
  components/userDashboard/Bookings.js
Labels: level2, gssoc23

#722 [Feature Request] - 'Sign Up' Form Input Area Improved Styling
  styles/form.module.css
  styles/userRegistration.module.css
Labels: level2, gssoc23

#745 Working of payment tab
  components/mentorDashboard/Payment.js
  components/mentorDashboard/PaymentComponent/Form.js
  styles/userRegistration.module.css
Labels: level3, gssoc23

#746 some fixes
  components/mentorDashboard/home.js
  components/mentorDashboard/profile.js
  components/mentorDashboard/sessions.js
  package.json
  pages/dashboard/mentor.page.js
Labels: gssoc23

#747 Session update
  .env
  components/layout/UserProfile.js
  components/mentorDashboard/home.js
  components/mentorDashboard/sessions.js
  package.json
  pages/dashboard/editMentorSession.page.js
Labels: gssoc23

#749 Coming soon page
  components/basic/ComingSoon.js
  pages/dashboard/mentor.page.js
Labels: gssoc23

#751 Adding loading state in dashboard
  components/mentorDashboard/Bookings.js
  components/mentorDashboard/Payment.js
  components/mentorDashboard/PreLoader.js
  components/mentorDashboard/QueriesComponent/ticketForm.js
  components/mentorDashboard/home.js
  components/mentorDashboard/profile.js
  components/mentorDashboard/queries.js
  components/mentorDashboard/sessions.js
  pages/dashboard/mentor.page.js
Labels: gssoc23

#753 created component edit sesssion!
  components/mentorDashboard/ListedSessionComponent/Form.js
  components/mentorDashboard/sessions.js
  components/newMentorProfile/SessionCard.js
Labels: gssoc23

#754 Image cropper component
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/components/PersonDetails.js
  components/basic/ImageCropper.js
  components/basic/ProfileImageInput.js
  components/mentorDashboard/PreLoader.js
  components/mentorDashboard/profile.js
  public/assets/img/RequestState/error.png
  public/assets/img/RequestState/loading.png
  styles/globals.css
Labels: gssoc23

#755 Added profile image input in user dashboard
  components/basic/ImageCropper.js
  components/mentorDashboard/profile.js
  components/userDashboard/profile.js
  pages/dashboard/mentor.page.js
  pages/dashboard/user.page.js
Labels: gssoc23

#674 Added alertbox
  components/basic/Alertbox.js
  pages/alertbox.page.js
Labels: gssoc23

#748 Mentor dashboard schedules
  components/mentorDashboard/CalendarComponent/card.js
  components/mentorDashboard/calendar.js
  components/mentorDashboard/sidebar.js
  pages/dashboard.page.js
  pages/dashboard/mentor.page.js
Labels: gssoc23

#757 Mentor Registration using Magic url
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/components/MagicUrlPopUp.js
  components/basic/Overlay.js
Labels: gssoc23

#758 feat: added toast.promise
  components/mentorDashboard/Bookings.js
  components/mentorDashboard/Payment.js
  components/mentorDashboard/home.js
  components/mentorDashboard/profile.js
  components/mentorDashboard/sessions.js
  pages/auth/login.page.js
  pages/blogDetail/[blogDetailId].page.js
  pages/dashboard/user.page.js
  styles/globals.css
Labels: gssoc23

#759 Revert "feat: added toast.promise"
  components/mentorDashboard/Bookings.js
  components/mentorDashboard/Payment.js
  components/mentorDashboard/home.js
  components/mentorDashboard/profile.js
  components/mentorDashboard/sessions.js
  pages/auth/login.page.js
  pages/blogDetail/[blogDetailId].page.js
  pages/dashboard/user.page.js
  styles/globals.css
Labels: gssoc23
