Repository anmode/grabtern-frontend, pull requests merged in 2023-07, with the labels that each got.

#474 [Feature Request] - Can Select Multiple Hackathon Tag #464
  components/hackthons/components/Searchbar.js
  pages/hackathon.page.js
  pages/index.page.js
Labels: level2, gssoc23

#484 refactored frontend for newSchema and implemented chaining
  components/Dashboard.js
  pages/[mentorUsername].page.js
  pages/dashboard.page.js
  pages/mentorLogin.page.js
Labels: gssoc23

#481 Refactoring 2
  components/UI/Button/Button.module.css
  components/UI/Card/IconCard.js
  components/UI/Card/ImageCard.js
  components/UI/Card/ProfileCard.js
  components/UI/Links/Link.module.css
  components/UI/Section/Section.js
  components/UI/Section/SectionHeader.js
  package.json
  pages/components.page.js
  public/assets/css/animated-headline.css
  public/assets/css/style.css
  styles/globals.css
  tailwind.config.js
Labels: level3, gssoc23

#372 Solved: New Navbar design and functionality also added dropdown card 🚀 [New Frontpage Issue#2] #296
  components/DarkModeToggle/DarkModeToggle.jsx
  components/basic/LoginDropdown.js
  components/layout/Header.js
  context/ThemeContext.js
  package.json
  pages/_app.page.js
  public/Grabtern2.png
  public/assets/css/style.css
  public/logo.png
  public/sitemap-0.xml
  styles/globals.css
  tailwind.config.js
Labels: enhancement, level3, gssoc23

#455 updated the mentors page
  components/newMentorProfile/SessionCard.js
  components/newMentorProfile/mentorAbout.js
  components/newMentorProfile/mentorTestimonial.js
  hook/useAPi.js
  next.config.js
  pages/[mentorUsername].page.js
  styles/globals.css
  styles/mentorTestimonial.module.css
Labels: gssoc23

#488 Refactoring 3
  components/UI/Card/ProfileCard.js
  components/UI/Form/Input.js
  components/UI/Links/ButtonLink.js
  components/UI/Section/Section.js
  components/UI/index.js
  components/layout/Footer.js
  components/layout/FooterColumn.js
  components/mentor.js
  pages/mentors.page.js
  styles/globals.css
  tailwind.config.js
Labels: level3, gssoc23

#498 Refactoring 4
  components/Testimonial.js
  components/UI/Button/Button.js
  components/UI/Card/ProfileCard.js
  components/UI/Section/Section.js
  components/mentor.js
  components/newMentorProfile/SessionCard.js
  components/newMentorProfile/mentorAbout.js
  components/newMentorProfile/mentorTestimonial.js
  pages/[mentorUsername].page.js
Labels: level3, gssoc23

#506 Homepage
  components/Banner.js
  pages/contact.page.js
  public/hero.svg
  styles/banner.module.css
Labels: level3, gssoc23

#505 fixed contact page in mobile width
  styles/contact.module.css
Labels: level1, gssoc23

#512 [Feature Request] - Optimizing Image cropper and reduce image while uploading
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/components/PersonDetails.js
  components/basic/Slider.js
Labels: level2, gssoc23

#508 Refactoring 5
  components/About.js
  components/Banner.js
  components/Internship.js
  components/Service.js
  components/TeamProfile.js
  components/Testimonial.js
  components/UI/Card/ImageCard.js
  components/UI/Card/ProfileCard.js
  components/UI/Section/Section.js
  components/hackthons/Hackathons.js
  components/homePage/About.js
  components/homePage/Banner.js
  components/homePage/Internship.js
  components/homePage/MentorSection.js
  components/homePage/Service.js
  components/homePage/TeamProfile.js
  components/homePage/Testimonial.js
  components/homePage/index.js
  components/layout/Header.js
  components/newMentorProfile/SessionCard.js
  components/newMentorProfile/mentorAbout.js
  pages/[mentorUsername].page.js
  pages/data/ServicesData.js
  pages/hackathon.page.js
  pages/index.page.js
  public/Hexagon.svg
  public/hero.svg
  styles/banner.module.css
  styles/globals.css
Labels: level3, GrabternTeam, gssoc23

#478 added mentorDashboard
  components/mentorDashboard/calendar.js
  components/mentorDashboard/profile.js
  components/mentorDashboard/sessions.js
  components/mentorDashboard/sidebar.js
  package.json
  pages/dashboard/mentor.page.js
  styles/sessions.module.css
  styles/sidebar.module.css
Labels: level3, gssoc23

#535 Encrypt/dcrypt
  .env
  components/Dashboard.js
  components/basic/LoginDropdown.js
  components/layout/Header.js
  components/user/login.js
  components/user/register.js
  hook/encryptDecrypt.js
  package.json
  pages/[mentorUsername].page.js
  pages/dashboard.page.js
  pages/hackathon.page.js
  pages/mentorLogin.page.js
Labels: gssoc23

#523 Aria attributes added to forms
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/components/ContactDetails.js
  components/MentorRegistration/components/PersonDetails.js
  components/MentorRegistration/components/ScheduleDetails.js
  components/MentorRegistration/components/SessionDetails.js
  components/user/login.js
  components/user/register.js
  pages/contact.page.js
  pages/mentorLogin.page.js
Labels: level2, gssoc23

#489 Complete date picker
  .env
  components/UI/Button/Button.js
  components/newMentorProfile/SessionCard.js
  components/user/login.js
  hook/encryptDecrypt.js
  pages/[mentorUsername].page.js
  pages/[mentorUsername]/bookSession/[sessionID].page.js
  pages/mentors.page.js
  public/assets/img/QR.png
  public/sitemap-0.xml
  styles/globals.css
Labels: gssoc23

#543 Fix datepicker errors
  .env
  pages/[mentorUsername].page.js
  pages/[mentorUsername]/bookSession/index.page.js
  styles/globals.css
Labels: gssoc23

#560 reset and forgot pass
  components/resetpassword.js
  pages/forgotpass.page.js
  public/assets/img/gif/Spinner.gif
Labels: gssoc23

#539 Added Scroll to top button
  components/basic/MoveToTop.js
  pages/_app.page.js
  pages/index.page.js
Labels: level2, gssoc23

#551 Fix User Profile icon issue of navbar
  components/homePage/Banner.js
  components/layout/Header.js
  components/layout/UserProfile.js
Labels: level3, gssoc23

#564 Created Sidebar for Mentor Dashboard
  components/mentorDashboard/sidebar.js
Labels: level3, gssoc23

#558 [WIP]: Added schedule page
  components/mentorDashboard/calendar.js
  styles/dashboard.module.css
Labels: gssoc23

#513 feat: add important meta elements to improve seo 🚀
  pages/_app.page.js
Labels: gssoc23

#568 Unused CSS file removal
  styles/MentorLogin.module.css
  styles/about.module.css
  styles/footer.module.css
  styles/mentorTestimonial.module.css
Labels: level3, gssoc23

#574 "no match found" in search query of mentors page
  pages/mentors.page.js
Labels: level2, gssoc23

#559 favicon changed to new logo
  pages/_app.page.js
  public/faviconn.png
Labels: level1, gssoc23

#575 fix page issues
  .env
  components/layout/UserProfile.js
  pages/auth/login.page.js
  pages/auth/register.page.js
  pages/index.page.js
Labels: gssoc23

#582 Unused CSS File Removal PR 2
  components/homePage/Banner.js
  components/homePage/MentorSection.js
  pages/_document.page.js
  pages/contact.page.js
  public/assets/css/flaticon.css
  public/assets/css/fontawesome-all.min.css
  public/assets/css/slick.css
  public/assets/css/slicknav.css
  public/assets/css/themify-icons.css
Labels: level3, gssoc23

#589 Fix datepicker
  pages/[mentorUsername]/bookSession/index.page.js
  pages/auth/forgotpass.page.js
Labels: gssoc23

#595 fix google not defined
  pages/_document.page.js
Labels: gssoc23

#583 revamp: list items design on homepage ✨
  components/UI/Card/IconCard.js
  components/homePage/About.js
  components/homePage/MentorSection.js
Labels: level1, gssoc23

#593 fix: moved community section to different page
  components/Community/CommunityCard.jsx
  components/layout/Header.js
  pages/community.page.js
  pages/index.page.js
Labels: gssoc23

#569 Added grabtern email feature in ReadMe
  README.md
Labels: level2, gssoc23

#522 Enhancing UI of Internship and Hackathon page
  components/AddIntership.js
  components/basic/Input.js
  components/hackthons/components/Searchbar.js
  package.json
  pages/data/coursesData.js
  pages/hackathon.page.js
  pages/internship.page.js
  styles/globals.css
Labels: level3, gssoc23

#586 arranged mentor page
  components/mentorPage/components/Company.js
  components/mentorPage/components/FAQ.js
  components/mentorPage/components/FAQList.js
  pages/data/faq.js
  pages/mentor.page.js
  public/assets/img/BecomeMentor.png
  public/assets/img/MentorImg.png
  public/assets/img/MentorImg.svg
  public/assets/index.js
Labels: level3, gssoc23

#573 feat: Font color change
  pages/privacy.page.js
  pages/refundandcancellation.page.js
  pages/termsandcondition.page.js
  styles/globals.css
Labels: gssoc23

#612 Create jest-test.yml
  .github/workflows/jest-test.yml
Labels: gssoc23

#610 feat: init Commlint✨
  .husky/commit-msg
  CONTRIBUTING.md
  commitlint.config.js
  package.json
Labels: level2, gssoc23

#616 Feat new logo#307
  README.md
  public/NewLogo.png
Labels: gssoc23

#588 Mentor Profile Page Added
  components/mentorDashboard/profile.js
Labels: level3, gssoc23

#618 Rename AddIntership to AddInternship
  components/AddInternship.js
Labels: gssoc23

#620 Single form modal for addInternship and addHackathon page
  components/AddHackathon.js
  components/AddInternship.js
  components/FormModal.js
  components/basic/Input.js
  pages/hackathon.page.js
  pages/index.page.js
  pages/internship.page.js
Labels: level3, gssoc23

#617 feat: testimonials section
  components/mentorPage/components/Company.js
  components/mentorPage/components/FAQ.js
  components/mentorPage/components/Testimonials.js
  pages/data/faq.js
  pages/data/testiomialsData.js
  pages/mentor.page.js
Labels: level3, gssoc23

#623 fixed reset password form submission and working
  components/mentorDashboard/profile.js
  components/mentorPage/components/Testimonials.js
  pages/auth/resetpassword.page.js
  pages/data/faq.js
  pages/mentor.page.js
  styles/globals.css
Labels: gssoc23

#635 registration to register
  pages/auth/register.page.js
Labels: gssoc23

#609 fix: lacking label for newsletter and incorrect way of displaying heading on login page 👷🏻🛠
  components/layout/Footer.js
  pages/auth/login.page.js
  styles/form.module.css
Labels: level1, gssoc23

#632 Fixed the confirmpassword visibility
  pages/auth/login.page.js
  pages/auth/register.page.js
  public/assets/Visibillity.jsx
  public/assets/VisibillityOff.jsx
Labels: level1, gssoc23
