Repository anmode/grabtern-frontend, pull requests merged in 2023-06, with the labels that each got.

#202 Fixed the Navbar height and user login page
  .gitignore
  components/Header.js
  pages/forgotpass.page.js
  pages/login.page.js
  pages/register.page.js
  public/assets/css/style.css
  public/sitemap-0.xml
  styles/LoginDropdown.module.css
  styles/globals.css
Labels: level 2

#191 @shivang-16 updated userLoginFormanMentorLoginForm
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  components/Footer.js
  styles/globals.css
Labels: level 2

#219 Fixed the broken UI as part of the defect(#217)
  styles/globals.css
Labels: level 1

#228 Hackathon Section Enhancement #198
  components/Hackathons.js
  pages/about.page.js
  pages/index.page.js
  public/assets/css/style.css
  styles/hackathon.module.css
Labels: level 2

#232 Contact module Created
  pages/_app.page.js
  pages/contact.page.js
  styles/contact.module.css
  styles/globals.css
Labels: level3

#247 UserAuth Logic Improvments and UI enhancement
  components/Header.js
  components/user/login.js
  components/user/register.js
  context/LogContext.js
  context/LogState.js
  package.json
  pages/_app.page.js
  pages/_document.page.js
  pages/login.page.js
  pages/register.page.js
  pages/userAuth.page.js
  postcss.config.js
  public/assets/css/bootstrap.min.css
  public/assets/css/style.css
  public/assets/img/gallery/20944201.webp
  public/sitemap-0.xml
  styles/globals.css
  tailwind.config.js
Labels: enhancement, help wanted, level3

#230 social media icons on mentor page
  components/Footer.js
  pages/mentors.page.js
  public/assets/css/main.css
  public/assets/css/style.css
  public/assets/css/style.map
  styles/LoginDropdown.module.css
  styles/footer.module.css
  styles/globals.css
Labels: level3

#229 Solved #75 : Added Dropdown Card
  components/Header.js
  components/LoginDropdown.js
  public/assets/css/main.css
  styles/LoginDropdown.module.css
  styles/globals.css
Labels: level3

#288 Fix Heading in Mentors Page
  pages/mentors.page.js
Labels: gssoc23

#290 Fixed Issue #265
  components/Internship.js
Labels: level1, gssoc23

#289 chore: add favicon and meta tags
  pages/_app.page.js
  pages/_document.page.js
Labels: gssoc23

#250 Separate module for registration.page.js is created
  styles/globals.css
  styles/userRegistration.module.css
Labels: level2, gssoc23

#280 Create Mentor Page
  components/mentorPage/Company.js
  components/mentorPage/FAQ.js
  components/mentorPage/FAQList.js
  components/mentorPage/IconCard.js
  components/mentorPage/Section.js
  pages/data/faq.js
  pages/mentor.page.js
  public/assets/css/style.css
  public/assets/img/company/GSoC.svg
  public/assets/img/company/hackerRank.svg
  public/assets/img/company/microsoft.svg
  public/assets/img/company/mlh.svg
Labels: level3, gssoc23

#310 Scrollbars removal
  styles/globals.css
Labels: level1, gssoc23

#315 Work on page name, Meta Tag, SEO , Name In URL
  package.json
  pages/[mentorUsername].page.js
  pages/_app.page.js
  pages/_document.page.js
  pages/contact.page.js
  pages/dashboard.page.js
  pages/forgotpass.page.js
  pages/index.page.js
  pages/mentor.page.js
  pages/mentorLogin.page.js
  pages/mentorRegister.page.js
  pages/mentorRegisterSendCV.page.js
  pages/mentors.page.js
  pages/privacy.page.js
  pages/refundandcancellation.page.js
  pages/termsandcondition.page.js
  pages/userAuth.page.js
  public/assets/img/favicon1.ico
Labels: level1, gssoc23

#302 Enhancing the UI of login dropdown buttons #292
  styles/LoginDropdown.module.css
  styles/globals.css
Labels: level1, gssoc23

#329 Infinite scroll/mentor list
  pages/mentors.page.js
Labels: gssoc23

#331 Solved #319 Improve Mentor Page and optimize for Mobile view. [GSSoC'23]
  components/Header.js
  components/mentorProfile/BookSessionModal.js
  components/mentorProfile/MentorCard.js
  components/mentorProfile/SessionCard.js
  components/mentorProfile/SharePageModal.js
  pages/[mentorUsername].page.js
Labels: level3, gssoc23

#340 fixed space in mentor page
  styles/globals.css
Labels: level1, gssoc23

#341 fix
  components/Header.js
  components/LoginDropdown.js
  components/user/login.js
  package.json
  pages/[mentorUsername].page.js
  pages/userAuth.page.js
  public/sitemap-0.xml
  styles/loader.module.css
Labels: gssoc23

#346 Infinite scroll/mentor list
  pages/mentors.page.js
Labels: gssoc23

#355 UX improve, session booking
  components/mentorProfile/MentorCard.js
  pages/[mentorUsername].page.js
Labels: gssoc23

#356 added react toastify in login mentorLogin and mentor Registration page
  components/Header.js
  components/MentorFormRegistration.js
  components/mentorProfile/MentorCard.js
  components/user/login.js
  pages/[mentorUsername].page.js
  pages/mentorLogin.page.js
  pages/mentors.page.js
  public/sitemap-0.xml
Labels: level3, gssoc23

#361 fix: 🐞 [BUG] - Icon translate #360
  public/assets/css/style.css
Labels: level1, gssoc23

#363 feature: To let the video just autoplay #362
  components/About.js
Labels: gssoc23

#368 OverflowRemoved
  styles/globals.css
Labels: level1, gssoc23

#376 fixing contact form
  pages/contact.page.js
Labels: level1, gssoc23

#374 Fixed isssue #222 added search bar
  pages/mentors.page.js
  styles/globals.css
Labels: level2, gssoc23

#366 Some fixes after release 2.0
  .env
  .gitignore
  components/MentorFormRegistration.js
  components/mentorProfile/SessionCard.js
  next.config.js
  pages/[mentorUsername].page.js
  public/assets/img/vector_images/image_1-removebg-preview.png
Labels: gssoc23

#345 Fixing profile image upload on mentor form registration
  components/ImageCropper.js
  components/MentorFormRegistration.js
  components/Slider.js
  package.json
  styles/slider.module.css
Labels: level3, gssoc23

#358 Enabled Client Side Caching #167
  components/Testimonial.js
  components/basic/spinner.js
  pages/customHook/useAPi.js
  pages/index.page.js
  pages/mentors.page.js
  public/sitemap-0.xml
  styles/globals.css
Labels: level3, gssoc23

#384 Mentor form Redesign
  components/MentorFormRegistration.js
  components/MentorRegistration/ContactDetails.js
  components/MentorRegistration/Input.js
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/PersonDetails.js
  components/MentorRegistration/ScheduleCard.js
  components/MentorRegistration/SessionDetails.js
  pages/mentorRegister.page.js
  public/assets/css/style.css
  styles/globals.css
Labels: level3, gssoc23

#320 New footer using tailwind css
  components/Footer.js
  components/Overlay.js
  postcss.config.js
  public/GrabternLogo.svg
  public/blacklogo.png
  styles/Overlay.module.css
  styles/footer.module.css
  tailwind.config.js
Labels: level3, OnHold, gssoc23

#397 Enhanced Mentor cards
  components/mentorProfile/MentorCard.js
Labels: level2, gssoc23

#404 Add CodeQL workflow
  .github/workflows/codeql.yml
  components/mentorProfile/MentorCard.js
Labels: level2, gssoc23

#402 component extraction ( mentor registration form)
  components/MentorRegistration/SessionDetails.js
  components/dateAndTime/DayInput.js
  components/dateAndTime/TimeZoneInput.js
Labels: level3, gssoc23

#408 New Footer using Tailwind css
  components/Footer.js
  components/Overlay.js
  components/mentor.js
  postcss.config.js
  styles/Overlay.module.css
  tailwind.config.js
Labels: level2, gssoc23

#399 Resolved Conflicts in #354
  components/About.js
  styles/about.module.css
  styles/globals.css
Labels: level2, gssoc23

#411 Readme is updated
  README.md
Labels: gssoc23

#406 Testimonials
  components/Testimonial.js
  pages/[mentorUsername].page.js
Labels: gssoc23

#427 Contact form validation checked before alert sent message issue
  package.json
  pages/contact.page.js
Labels: level2, gssoc23

#434 Add Session Details Step in Mentor Registration Form
  components/MentorRegistration/Card.js
  components/MentorRegistration/Input.js
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/ScheduleCard.js
  components/MentorRegistration/ScheduleDetails.js
  components/MentorRegistration/SessionDetails.js
Labels: level3, gssoc23

#438 corrected grammatical error
  pages/mentors.page.js
Labels: level1, gssoc23

#424 Mentor form validation
  components/MentorRegistration/ContactDetails.js
  components/MentorRegistration/Input.js
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/PersonDetails.js
  components/MentorRegistration/ScheduleDetails.js
  components/MentorRegistration/SessionDetails.js
  package.json
  styles/globals.css
Labels: level3, gssoc23

#439 Removed previous commits
  components/mentor.js
  styles/globals.css
Labels: level3, gssoc23

#409 Added show password button
  components/user/login.js
  components/user/register.js
  pages/mentorLogin.page.js
  public/assets/Visibillity.jsx
  public/assets/VisibillityOff.jsx
  public/assets/css/style.css
Labels: level3, gssoc23

#450 refactored mentor registration for new Scema
  components/MentorRegistration/MentorFormRegistration.js
Labels: gssoc23

#436 FInal Update
  components/Searchbar.js
  package.json
  pages/data/hackathonsData.js
  pages/hackathon.page.js
  pages/index.page.js
  public/assets/img/hackathons/689.webp
  public/assets/img/hackathons/917.webp
  public/assets/img/hackathons/Google Girl Hackathon.webp
  public/assets/img/hackathons/SIH.webp
  public/assets/img/hackathons/Solve for Tomorrow.webp
  public/assets/img/hackathons/Solve_for_Tomorrow_346x219_1_346x210_1_346x205_1_346x202_1_346x200.webp
  public/assets/img/hackathons/codecrush.webp
  public/assets/img/hackathons/gcccode.webp
  public/assets/img/hackathons/girls3_384x219.webp
  public/assets/img/hackathons/image.webp
  public/assets/img/hackathons/north.webp
  public/assets/img/hackathons/p_1178x720.webp
  public/assets/img/hackathons/q5_2_1173x720.webp
  styles/hackathon.module.css
Labels: level3, gssoc23

#445 Use overlay on mentor registration form
  components/MentorRegistration/MentorFormRegistration.js
  components/MentorRegistration/PersonDetails.js
  components/Overlay.js
  styles/Overlay.module.css
Labels: level3, gssoc23

#435 Contact us improved
  pages/contact.page.js
  styles/contact.module.css
Labels: level3, gssoc23
