Repository anmode/grabtern-frontend, pull requests merged in 2023-05, with the labels that each got.

#152 Update feature_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: good first issue, gssoc2023

#176 Responsive the Mentor & Contact us page for all devices
  .github/workflows/greetings.yml
  components/mentor.js
  public/assets/css/style.css
  styles/globals.css
Labels: level 3

#190 Tech Stack Section Added
  README.md
Labels: level 2
