Repository anmode/grabtern-frontend, pull requests merged in 2024-10, with the labels that each got.

#873 fix(scroll): fix scrolling behavior | Issue #854
  components/basic/MoveToTop.js
Labels: level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#860 fix(twitter-icon): updated twitter icon and fixed unrelated changes
  .gitattributes
  components/layout/Footer.js
Labels: bug, level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#879 fix(spinner): center spinner and enhance design
  components/UI/MainLoader.js
Labels: bug, level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#883 Navbar icons
  components/layout/Header.js
  package.json
Labels: enhancement, level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#888 fix(card): fix inconsistent card size
  components/homePage/Testimonial.js
Labels: bug, level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#889 fix: chat icon opacity and alignment
  components/support/SupportChat.js
Labels: bug, level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#896 style: added scrollbar to homepage
  styles/globals.css
Labels: enhancement, level1, hacktoberfest, hacktoberfest-accepted, gssoc-ext
